import { useState } from 'react';
import { ScrollView, TextInput, View, StyleSheet } from 'react-native';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Button, Card, Header, Screen, Text } from '../../components/ui';
import { legalApi, pqrsApi } from '../../services/endpoints'; import { useTheme } from '../../hooks/useTheme'; import { Spacing } from '../../theme/tokens';
const TYPES = [['petition','Petición'],['complaint','Queja'],['claim','Reclamo'],['suggestion','Sugerencia']] as const;
export default function RequestsScreen() { const { c } = useTheme(); const qc = useQueryClient(); const [kind, setKind] = useState<'pqrs'|'data'>('pqrs'); const [type, setType] = useState('petition'); const [subject, setSubject] = useState(''); const [detail, setDetail] = useState(''); const { data: pqrs = [] } = useQuery({ queryKey: ['pqrs'], queryFn: pqrsApi.mine }); const { data: dataRequests = [] } = useQuery({ queryKey: ['data-requests'], queryFn: legalApi.dataRequests }); const save = useMutation({ mutationFn: () => kind === 'pqrs' ? pqrsApi.create(type, subject, detail) : legalApi.createDataRequest(type, detail), onSuccess: () => { setSubject(''); setDetail(''); qc.invalidateQueries({ queryKey: [kind === 'pqrs' ? 'pqrs' : 'data-requests'] }); } });
  const options = kind === 'pqrs' ? TYPES : [['access','Consultar/copia'],['rectify','Corregir'],['update','Actualizar'],['delete','Suprimir'],['revoke','Revocar']] as const;
  return <Screen><Header title="PQRS y datos" fallback="/(client)/settings"/><ScrollView contentContainerStyle={styles.content}><View style={styles.tabs}><Button title="PQRS" variant={kind === 'pqrs' ? 'primary' : 'secondary'} onPress={() => { setKind('pqrs'); setType('petition'); }}/><Button title="Mis datos" variant={kind === 'data' ? 'primary' : 'secondary'} onPress={() => { setKind('data'); setType('access'); }}/></View><Card style={styles.card}><Text v="titleM">Nueva solicitud</Text><View style={styles.tabs}>{options.map(([value,label]) => <Button key={value} title={label} size="sm" variant={type === value ? 'primary' : 'secondary'} onPress={() => setType(value)} />)}</View>{kind === 'pqrs' && <TextInput value={subject} onChangeText={setSubject} placeholder="Asunto" placeholderTextColor={c.textMuted} style={[styles.input,{color:c.text,borderColor:c.border}]} /> }<TextInput value={detail} onChangeText={setDetail} multiline placeholder="Describe tu solicitud" placeholderTextColor={c.textMuted} style={[styles.input,styles.detail,{color:c.text,borderColor:c.border}]} /><Button title="Enviar solicitud" full loading={save.isPending} disabled={detail.trim().length < 10 || (kind === 'pqrs' && subject.trim().length < 3)} onPress={() => save.mutate()} /></Card><Text v="label" tone="textMuted">Historial</Text>{(kind === 'pqrs' ? pqrs : dataRequests).map((x:any) => <Card key={x._id} style={styles.card}><Text v="strongS">{x.subject || x.type}</Text><Text v="caption" tone="textMuted">Estado: {x.status}</Text><Text v="bodyS" tone="textSecondary">{x.response || x.detail}</Text>{x.responses?.map((r:any,i:number)=><Text key={i} v="bodyS">ZIPP: {r.message}</Text>)}</Card>)}</ScrollView></Screen>; }
const styles=StyleSheet.create({content:{padding:Spacing.xl,gap:Spacing.md,paddingBottom:Spacing.huge},tabs:{flexDirection:'row',flexWrap:'wrap',gap:Spacing.sm},card:{gap:Spacing.sm},input:{borderWidth:1,borderRadius:12,padding:12},detail:{minHeight:100,textAlignVertical:'top'}});
