import { Router } from 'express';
import authRoutes from './auth.routes';
import businessRoutes from './business.routes';
import orderRoutes from './order.routes';
import productRoutes from './product.routes';
import driverRoutes from './driver.routes';
import adminRoutes from './admin.routes';
import categoryRoutes from './category.routes';
import addressRoutes from './address.routes';
import securityRoutes from './security.routes';
import reviewRoutes from './review.routes';
import notificationRoutes from './notification.routes';
import couponRoutes from './coupon.routes';
import zoneRoutes from './zone.routes';
import paymentRoutes from './payment.routes';
import financeRoutes from './finance.routes';
import legalRoutes from './legal.routes';
import pqrsRoutes from './pqrs.routes';
import advertisementRoutes from './advertisement.routes';
import promotionBannerRoutes from './promotionBanner.routes';
import homeCategoryRoutes from './homeCategory.routes';
import rbacRoutes from './rbac.routes';
import trackingRoutes from './tracking.routes';
import searchRoutes from './search.routes';
import offersRoutes from './offers.routes';
import favoriteRoutes from './favorite.routes';
import loyaltyRoutes from './loyalty.routes';
import referralRoutes from './referral.routes';
import sosRoutes from './sos.routes';
import errandRoutes from './errand.routes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/businesses', businessRoutes);
router.use('/orders', orderRoutes);
router.use('/products', productRoutes);
router.use('/drivers', driverRoutes);
router.use('/admin', adminRoutes);
router.use('/categories', categoryRoutes);
router.use('/addresses', addressRoutes);
router.use('/security', securityRoutes);
router.use('/reviews', reviewRoutes);
router.use('/notifications', notificationRoutes);
router.use('/coupons', couponRoutes);
router.use('/zones', zoneRoutes);
router.use('/payments', paymentRoutes);
router.use('/finance', financeRoutes);
router.use('/legal', legalRoutes);
router.use('/pqrs', pqrsRoutes);
router.use('/advertisements', advertisementRoutes);
router.use('/promotion-banners', promotionBannerRoutes);
router.use('/home-categories', homeCategoryRoutes);
router.use('/rbac', rbacRoutes);
router.use('/tracking', trackingRoutes);
router.use('/search', searchRoutes);
router.use('/offers', offersRoutes);
router.use('/favorites', favoriteRoutes);
router.use('/loyalty', loyaltyRoutes);
router.use('/referrals', referralRoutes);
router.use('/sos', sosRoutes);
router.use('/errands', errandRoutes);

export default router;
